name: PyTest

on:
    push:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"
            - name: Install
              run: |
                python -m pip install --upgrade pip poetry
                poetry config virtualenvs.create false
                poetry install
            - name: Running pytest under coverage
              run: |
                coverage run -m pytest tests
                coverage html
            - name: Upload coverage report
              uses: actions/upload-artifact@v4
              with:
                name: coverage_report
                path: htmlcov/